import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#4834D4",
        "on-background": "#191c1e",
        "primary-fixed": "#e3dfff",
        "tertiary-fixed": "#eaddff",
        "surface-container-low": "#f3f4f6",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#85f8c4",
        tertiary: "#4c00aa",
        "primary-fixed-dim": "#c5c0ff",
        "on-surface": "#191c1e",
        surface: "#f8f9fb",
        "on-primary-container": "#ffffff",
        "tertiary-container": "#6719d8",
        "surface-variant": "#e1e2e4",
        "on-surface-variant": "#474555",
        "surface-container-highest": "#e1e2e4",
        "secondary-container": "#82f5c1",
        "on-tertiary-fixed": "#25005a",
        "surface-tint": "#4834D4",
        "on-primary": "#ffffff",
        "primary-container": "#4834D4",
        "on-secondary-container": "#00714e",
        "on-primary-fixed": "#140067",
        "on-error": "#ffffff",
        "surface-container-high": "#e7e8ea",
        "surface-container-lowest": "#ffffff",
        outline: "#787587",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#3b22c8",
        "secondary-fixed-dim": "#68dba9",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005137",
        background: "#f8f9fb",
        "tertiary-fixed-dim": "#d2bbff",
        "outline-variant": "#c8c4d8",
        "on-tertiary-fixed-variant": "#5a00c6",
        "on-tertiary-container": "#d2bbff",
        "on-secondary-fixed": "#002114",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f3",
        "surface-container": "#edeef0",
        "surface-dim": "#d9dadc",
        "surface-bright": "#f8f9fb",
        "inverse-primary": "#c5c0ff",
        secondary: "#006c4a",
        error: "#ba1a1a"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Manrope"],
        label: ["Manrope"],
        sans: ["Manrope", "system-ui", "sans-serif"],
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      }
    },
  },
  plugins: [],
}
export default config